name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: Build
    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - name: Update rider version from Directory.Build.props
      run: .\Abc.MoqComplete\Deployment\update_rider_version.ps1
      shell: powershell

    - name: Clean
      run: dotnet clean Abc.MoqComplete\MoqComplete.sln --configuration Release && dotnet nuget locals all --clear

    - name: Install dependencies
      run: dotnet restore Abc.MoqComplete\MoqComplete.sln

    - name: Build
      run: dotnet build Abc.MoqComplete\MoqComplete.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test Abc.MoqComplete\Abc.MoqComplete.Tests\bin\Abc.MoqComplete.Tests\Release\Abc.MoqComplete.Tests.dll --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack Abc.MoqComplete\MoqComplete.sln --no-build --no-restore -c Release -o out

    - name: Fix rider plugin
      run: .\Abc.MoqComplete\Deployment\build_rider_plugin.ps1 out
      shell: powershell

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BuildResult
        path: out

